### ISSUE TITLE
Create story map

### ISSUE THREAD

**Issue by charlyol** [charlyol/ECommerce-SCHA#3]

**Comment by charlyol** [comment]
Create the story map for make a E.Commerce web site

**Comment by charlyol** [comment]
theme = sell box

**Comment by AugustinPech** [comment]
[798648357737-8809119489-billet.pdf](https://github.com/charlyol/ECommerce-SCHA/files/14280052/798648357737-8809119489-billet.pdf)

**Comment by AugustinPech** [comment]
[SCHA Story Map.pdf](https://github.com/charlyol/ECommerce-SCHA/files/14280055/SCHA.Story.Map.pdf)
